version: "3"

services:
  pihole-crypt:
    container_name: pihole-crypt
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "6680:80/tcp"
      - "6443:443/tcp"
    environment:
      - DNS1="127.0.0.1#5399"
    #  - ServerIP=192.168.0.60
      - TZ='Europe/London'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./data/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./data/data-pihole:/data
    restart: unless-stopped
  
  dns-crypt:
    container_name: dnsproxy
    image: chrisbensch/docker-dnsproxy
    #docker run -p 127.0.53.53:53:53/udp -e 'DNSPROXY_UPSTREAM=quic://dns.emeraldonion.org:8853' -e 'DNSPROXY_BOOTSTRAP=9.9.9.9' emeraldonion/docker-dnsproxy
    environment:
      - DNSPROXY_UPSTREAM="quic://dns.emeraldonion.org:8853"
      - DNSPROXY_BOOTSTRAP="9.9.9.9"
    ports:
      - 127.0.53.53:5399:53/udp
    #volumes:
    #  - ./data/data-dnsproxy:/data
    restart: unless-stopped
